const express = require('express');
const cors = require('cors');
const dotenv = require('dotenv');
const http = require('http');
const { Server } = require('socket.io');
const jwt = require('jsonwebtoken');
const connectDB = require('./config/db');
const User = require('./models/User');
const { getJwtSecret, mongoSanitize } = require('./middleware/security');

// Load env vars
dotenv.config();

// Fail fast if JWT secret is missing in production
getJwtSecret();

// Connect to database
connectDB();

// Allowed browser origins (comma-separated). Localhost is always allowed outside production.
const allowedOrigins = (process.env.CORS_ORIGINS || 'https://smileflow-frontend.onrender.com')
  .split(',').map(o => o.trim()).filter(Boolean);
const corsOrigin = (origin, cb) => {
  if (!origin) return cb(null, true); // same-origin, curl, mobile apps
  if (allowedOrigins.includes(origin)) return cb(null, true);
  if (process.env.NODE_ENV !== 'production' && /^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(origin)) return cb(null, true);
  return cb(null, false);
};

const app = express();
app.disable('x-powered-by');
app.set('trust proxy', 1); // correct req.ip behind Render/Vercel proxy (rate limiting)
const server = http.createServer(app);
const io = new Server(server, {
  cors: {
    origin: corsOrigin,
    methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE']
  }
});

// Map to track active users: userId -> array of socketIds
const onlineUsers = new Map();

// Socket.io JWT authentication middleware
io.use(async (socket, next) => {
  try {
    const token = socket.handshake.auth.token || socket.handshake.query.token;
    if (!token) {
      return next(new Error('Authentication error: No token provided'));
    }
    const decoded = jwt.verify(token, getJwtSecret());
    const user = await User.findById(decoded.id).select('-password');
    if (!user) {
      return next(new Error('Authentication error: User not found'));
    }
    socket.user = user;
    next();
  } catch (err) {
    next(new Error('Authentication error: Token invalid'));
  }
});

// Handle Socket.io connection
io.on('connection', (socket) => {
  const userId = socket.user._id.toString();
  
  if (!onlineUsers.has(userId)) {
    onlineUsers.set(userId, []);
  }
  onlineUsers.get(userId).push(socket.id);
  console.log(`Socket Connected: ${socket.user.name} (${userId})`);

  socket.emit('joined', { userId });

  socket.on('disconnect', () => {
    if (onlineUsers.has(userId)) {
      const remainingSockets = onlineUsers.get(userId).filter(id => id !== socket.id);
      if (remainingSockets.length === 0) {
        onlineUsers.delete(userId);
      } else {
        onlineUsers.set(userId, remainingSockets);
      }
    }
    console.log(`Socket Disconnected: ${socket.user.name}`);
  });
});

// Middleware
app.use(cors({ origin: corsOrigin }));
// Voice notes, voicemails and task attachments are sent as base64, so allow larger bodies.
app.use(express.json({ limit: '10mb' }));
app.use(mongoSanitize);

// Share socket io and online users map with our routes
app.use((req, res, next) => {
  req.io = io;
  req.onlineUsers = onlineUsers;
  next();
});

// Suppress 404 errors generated by browser extensions (e.g., Grammarly, Password Managers, IDE previews)
// These extensions often ping /api/ext/activate or /api/ext/auth-token
app.all('/api/ext/*splat', (req, res) => {
  res.status(200).json({ success: true, message: 'Extension endpoint bypassed' });
});

// Routes
app.use('/api/auth', require('./routes/authRoutes'));
app.use('/api/patients', require('./routes/patientRoutes'));
app.use('/api/appointments', require('./routes/appointmentRoutes'));
app.use('/api/tasks', require('./routes/taskRoutes'));
app.use('/api/staff', require('./routes/staffRoutes'));
app.use('/api/attendance', require('./routes/attendanceRoutes'));
app.use('/api/leave', require('./routes/leaveRoutes'));
app.use('/api/voicemails', require('./routes/voicemailRoutes'));
app.use('/api/settings', require('./routes/clinicSettingRoutes'));
app.use('/api/messages', require('./routes/messageRoutes'));
app.use('/api/audit-logs', require('./routes/auditLogRoutes'));

app.get('/', (req, res) => {
  res.send('Smile Flow API is running...');
});

// JSON 404 for unknown API routes
app.use('/api', (req, res) => {
  res.status(404).json({ message: `Route not found: ${req.method} ${req.originalUrl}` });
});

// Central error handler (malformed JSON, payload too large, unexpected errors)
// eslint-disable-next-line no-unused-vars
app.use((err, req, res, next) => {
  if (err.type === 'entity.parse.failed') {
    return res.status(400).json({ message: 'Malformed JSON in request body' });
  }
  if (err.type === 'entity.too.large') {
    return res.status(413).json({ message: 'Request body too large' });
  }
  console.error('Unhandled error:', err);
  res.status(err.status || 500).json({ message: 'Internal server error' });
});

process.on('unhandledRejection', (reason) => {
  console.error('Unhandled promise rejection:', reason);
});

const PORT = process.env.PORT || 5000;

server.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

